### PR TITLE
Added extra regexes to match release names for a.b.anime,

### PR DESCRIPTION
**Pull request by nightah**
Changes made by this pull request.
- Included two new release naming regexes for anime

Regex tests below (obviously global and multi line are only turned on for the purpose of the test):
1161: https://regex101.com/r/Yus6Jo/4
1162: https://regex101.com/r/3sysKA/5

### CODE REVIEW

**Comment by nightah** [comment]
Included https://github.com/nZEDb/nZEDb/pull/2440/commits/ec474e9b01456f07fde7a0b6b40e3af2bad80f9b to catch releases like such:
//[DB] Inou-Battle wa Nichijou-kei no Naka de | When Supernatural Battles Became Commonplace [Dual Audio 10bit BD720p][HEVC-x265] [1/5] - " [DB]When Supernatural Battles Became Commonplace _-_07_(Dual Audio_10bit_BD720p_x265).mkv" yEnc

Also updated the test regex above in 1162.

**Comment by niel** [comment]
@nightah are there any situations where the white space added by https://github.com/nZEDb/nZEDb/pull/2440/commits/ec474e9b01456f07fde7a0b6b40e3af2bad80f9b would prevent matching? i.e. do these get posted without a space included at that position?

Arrgh!! forget I asked. I see you're modifying your own new regex to allow for optional white-space.
I'll merge these in tomorrow.

**Comment by nightah** [comment]
@niel I didn't notice any problems with my subsequent testing because the white space is matched with a ? quantifier. Both those with and without spaces were posted.

It's more common for the releases to not include the white space after the first ". However after doing a couple rounds of testing I noticed that occasionally there would be the odd white space after the first ".

The regex catches the most common type of post (without the white space) and also the odd one here and there with the white space as an optional, as per https://regex101.com/r/3sysKA/5.

Realistically https://github.com/nZEDb/nZEDb/pull/2440/commits/ec474e9b01456f07fde7a0b6b40e3af2bad80f9b is just housekeeping because of my OCD, seeing a space in the release name that shouldn't be there irks me.

**Comment by nightah** [comment]
Just came across another case too with a - this time. Will be adding a commit to catch this:

//[DB] Mob Psycho 100 [Dual Audio 10bit 720p][HEVC-x265] [1/6] - "-[DB]Mob Psycho 100 _-_09_(Dual Audio_10bit_HDTV720p_x265).mkv" yEnc

**Comment by nightah** [comment]
https://github.com/nZEDb/nZEDb/pull/2440/commits/3f82468e2c5686f6ba850a54311af6d9f7453667 added another case to https://regex101.com/r/3sysKA/6

**Pull request merged**
