### PR TITLE
Update DbUpdate.php

### PR DESCRIPTION
**Pull request by cauchy49**
when local, the sql should be "LOAD DATA LOCAL"
incorrect test : reverse it...

### CODE REVIEW

**Comment by ruhllatio** [comment]
@cauchy49 thanks for the PR, but we cannot accept merges to the master branch.  They have to go to the dev branch first.  Please re-open the PR and do a compare/pull request to the dev branch instead.

**Comment by ruhllatio** [comment]
Wow, should have looked at it first too.  LOCAL is not actually for local DB servers.  It's to tell the MySQL client that the data file is local to the client while the server is remote.  Otherwise the Server searches for the file locally and fails to find said file.

**Comment by cauchy49** [comment]
my sql server is local, and without this change I have a "permission denied" from mysql (permissions on directory afile are ok) when i try to configure the database (in step2.php). Maybe LOCAL must be always used...

**Comment by ruhllatio** [comment]
Are you SURE you added the GRANT FILE rights?

**Comment by niel** [comment]
if LOCAL were always used it would change how MySQL looks for the file and cause other problems. Additionally, extra permissions would be required by the user.

**Comment by cauchy49** [comment]
yes, i try with root and nzedb account :

global permissions are  (from phpmyadmin) :

nzedb	localhost	Oui	SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, __FILE__

**Comment by niel** [comment]
Check all the directories in the path to your files have the Traversible bit set, and the files are readable by all.

**Pull request closed without merging**
