### PR TITLE
Various fixes for web templates

### PR DESCRIPTION
**Pull request by JReming85**
Add First/Last name to the Profile/Profile Edit page of the themes that were missing it.

* This fix allows a user that has chosen a theme that currently does not use those fields from having their First/Last name being overwritten with ""
[image](https://user-images.githubusercontent.com/21246660/47456923-c20be280-d7a3-11e8-92ef-d957b767821c.png)

Fixed pnotify & iphone toggle js path for Charisma Theme

Fix Searchbox & button size/placement to match the rest of the layout mainly for Gentele

* [image](https://user-images.githubusercontent.com/21246660/47456816-7a855680-d7a3-11e8-9af5-bd20dedccb69.png)

Create a custom css file for Gentele

Add Video Preview Tab for Charisma
* [image](https://user-images.githubusercontent.com/21246660/47456747-545fb680-d7a3-11e8-99d2-dfc07968d5b9.png)

Add more tags to each release for Charisma

* Password Status, Video Preview, IMDB Info, Music Info, Mediainfo, PreDB
[image](https://user-images.githubusercontent.com/21246660/47456722-40b45000-d7a3-11e8-8bea-995f1c26d08a.png)

Add login button to menu for Charisma
* [image](https://user-images.githubusercontent.com/21246660/47456645-0945a380-d7a3-11e8-99ab-2b11c933115d.png)

Add New Column for Covers for TV & Movies

* For non cover view, with the exception of anime, will create a new column named Covers, and display the available show/movie cover. 
[image](https://user-images.githubusercontent.com/21246660/47456567-e74c2100-d7a2-11e8-9b6a-bd070bc152b6.png)

* with full table for tv
[image](https://user-images.githubusercontent.com/21246660/47457151-570edb80-d7a4-11e8-9db3-6cd1a1076fea.png)

* with full table for movies
[image](https://user-images.githubusercontent.com/21246660/47457231-950bff80-d7a4-11e8-909c-97eef1478a34.png)

Fixed table sorting for Charisma and added it to all columns except for Cover

Hopefully this pull is acceptable, if not let me know what needs to be changed.

Thanks

### CODE REVIEW

**Comment by DariusIII** [comment]
This PR looks fine to me.

**Comment by Bart39** [comment]
pull requests must be made against the dev branch and not master - please recreate your pull request against the correct branch

**Comment by DariusIII** [comment]
Oh, i did not see that PR was against 0.x.

**Comment by JReming85** [comment]
Sorry about that,

Will go ahead and make the change asap

**Comment by niel** [comment]
While you are making that change, please keep PRs to one fix/feature. I'd appreciate limiting the PRs to one Theme and spreading them across multiple PRs, *unless* a fix applies to all themes - in which case put that in a separate PR

**Pull request closed without merging**
