### PR TITLE
Fix the nzbFileList function, as it was causing  PHP Fatal error:  Un…

### PR DESCRIPTION
**Pull request by DariusIII**
…supported operand types

### CODE REVIEW

**Comment by Wally73** [comment]
i'm running the latest dev for the last 3 hours and  i haven't gotten any php fatal errors (or any error) 
PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27)

**Comment by DariusIII** [comment]
Have you turned on the new rar option?

**Comment by Wally73** [comment]
yes i have that enabled

http://gyazo.com/408785f376f10ecdbed339ca54938345

**Comment by Wally73** [comment]
needs to be merged indeed. Error showed up in php_error.log and the list contents of the rar gave an empty page

**Pull request merged**
