### PR TITLE
New release name format not matched with reqid

### PR DESCRIPTION
**Pull request by rainje**
Addresses issue #.
## 
## 

Used to be XXXXX-X[XX/XX] - "XXXXX-X.par2" yEnc, now comes in XXXXX-X [XX/XX] - "XXXXX-X.par2"

### CODE REVIEW

**Comment by rainje** [comment]
Looks like it's not working, theses posts keep getting into other>misc.

Eg: posts in ab.mom 
etc

Looking up Git tag version(s)
Hash: da7262e3880aef7f4170cf615dc44b20aaca397e
XML version: 0.6.0
Git version: v0.6.0-1

Looking up SQL patch version(s)
XML version: 430
 DB version: 430

**Comment by Wally73** [comment]
mom is never looked up afaik (most in mom is crap or reposts from teevee with passwords)

**Comment by rainje** [comment]
It is, mostly for foreign stuff.

https://github.com/nZEDb/nZEDb/search?utf8=%E2%9C%93&q=alt.binaries.mom

**Comment by Bart39** [comment]
there's a problem with the trigger change - looking at it

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/commit/75628b65c3d370980b15b1a971cda921ba609b5d

**Pull request merged**
