### PR TITLE
Add option to admin area to allow/dissalow users to select their site…

### PR DESCRIPTION
**Pull request by DariusIII**
… theme.

### CODE REVIEW

**Comment by niel** [comment]
I do not see the point of this option.
On a personal level, I do not believe in removing options from users and forcing them to work they way the admin insists.
If you *must* remove the options, remove the templates so they're not available.

**Comment by DariusIII** [comment]
This option is mainly pointed at admins that customize their templates. As per all the settings, nobody forces admins to use it. While i understand your point and agree to some level, it is still a viable option.

**Comment by niel** [comment]
As I said, the option already exists. The admin can remove the templates if they want to prevent their use. Alternatively they could merge this PR themselves.
I don't believe this should exist in the core. It is for individual site admins to customise this kind of option themselves.

**Comment by niel** [comment]
I would be more inclined to consider an option that restricts the templates individually. In effect virtually deleting them from the available ones.

**Comment by Fossil01** [comment]
It's such a small change which might help a lot of site owners. Why not just merge it and be done with it? No effort at all. I for example like to keep the default/alpha theme around when I need to test something real quick.

**Pull request closed without merging**
