### PR TITLE
Move Other cats to 0000 range, books cat to 7000 range.

### PR DESCRIPTION
**Pull request by DariusIII**

### CODE REVIEW

**Comment by Wally73** [comment]
dont see a reason for this just move the category other stuff all to all other (7000) think then less scripts etc has to be changed (but ok that is my opinion)

**Comment by DariusIII** [comment]
It is more than a move, there is no logic for misc cats to be between xxx and books, and moving books to 7k range is a logical step.

**Comment by DariusIII** [comment]
I have made a change so Books class will use constants from Category instead of numbers for category ids.

**Comment by niel** [comment]
I thought you were going to change all uses of numbers in code to use constants?

**Comment by DariusIII** [comment]
I changed to constants where i could. The rest of the code is appending stuff to queries to build them, and i am not familiar in a way to make it use constants, and to not break those.

**Comment by DariusIII** [comment]
With help @Bart39 i have fixed the rest of the queries and updated the PR.

**Comment by niel** [comment]
Sweet. I'll look at it ASAP

**Pull request merged**
