### PR TITLE
Lithium Connections

### PR DESCRIPTION
**Pull request by josh4trunks**
Correctly passes parameters based on what lithium is expecting.
See https://github.com/UnionOfRAD/lithium/blob/1.1/data/source/database/adapter/MySql.php#L173-190

Fixes https://github.com/nZEDb/nZEDb/issues/2133 for all cases.

### CODE REVIEW

**Comment by niel** [comment]
I don't understand this PR. What is it, that this is intended to achieve, that is currently missing?
Incidentally our coding policy doesn't permit complex ternaries, they are too complicated to read and often act differently to the intended action.

**Comment by josh4trunks** [comment]
The current code doesn't pass the parameters correctly. I mentioned this before but I don't think it was noticed.
Lithium is expecting the host and port to be passed in the host variable like so

```
host=MYSQL_HOSTNAME:1234
```

Lithium doesn't use the socket or port variable.

I don't like the complex ternary either, just wanted to keep in line with what you had. I can change this to a normal if/else statement.

**Comment by josh4trunks** [comment]
See this post, where I show what we should be passing to lithium
https://github.com/nZEDb/nZEDb/issues/2133#issuecomment-225236131

**Comment by josh4trunks** [comment]
Ok, using standard if/else

**Comment by niel** [comment]
I must be missing something. I looked at the Lithium code and as far as I can see it does NOT expect host:port in the host parameter.
https://github.com/UnionOfRAD/lithium/blob/1.1/data/source/database/adapter/MySql.php#L184 creates the dsn from both host and port settings.

Admittedly, the code before that is somewhat confusing as to its intent.

**Comment by josh4trunks** [comment]
What you are looking at is the stuff after parsing. The only variable lithium pulls from configuration is host, which is parsed here https://github.com/UnionOfRAD/lithium/blob/1.1/net/HostString.php#L29

**Comment by josh4trunks** [comment]
Here's the developers comment on it
https://github.com/UnionOfRAD/lithium/issues/1273#issuecomment-222825933

**Comment by niel** [comment]
I was just reading the the Hostname class code. I think you're right, but I'll look at it a bit longer to be sure I'm getting it right.

**Comment by josh4trunks** [comment]
Sounds good, take your time. Doesn't affect me until dev is merged in 0.x anyway.

**Comment by niel** [comment]
Patch still misses one possibility. According to the Hostname class documentation it can accept ":<port>" and will automatically add the default host value.

**Comment by niel** [comment]
BTW single level ternaries are acceptable. So the second level of that if structure can be a ternary.

**Comment by josh4trunks** [comment]
I assumed nZEDb didn't accept that case so I didn't worry about it, but feel free to take over.

Ahh, I was thinking I could implement a ternary somewhere, but those are pretty new to me =]

**Comment by josh4trunks** [comment]
sweet, looking forward to the next merge of dev

**Pull request merged**
