### PR TITLE
Add Regexes for Korean Newsgroups

### PR DESCRIPTION
**Pull request by izolight**
I created some regexes that help finding releases in korean Newsgroups.

### CODE REVIEW

**Comment by izolight** [comment]
How come the collections are created without those?

**Comment by DariusIII** [comment]
They are, that is true, but it would be nice from you to add korean groups specific regexes where they don't exist. I did not mean to piss you off or anything, it was just a badly worded suggestion.

**Comment by izolight** [comment]
Oh I see. I guess my answer was equally badly worded, just trying to understand how nzedb works :). What kind of regexes are used if I don't have group specific collection regexes, so I don't create duplicates?

**Comment by kevinlekiller** [comment]
Thanks izolight, can you possibly remake this without those extra commits from @bfincher and @DariusIII ? Would make it easier to see what is actually changed.

**Pull request closed without merging**
