### PR TITLE
Fix movie covers on alpha theme, add first batch of changes to omicro…

### PR DESCRIPTION
**Pull request by DariusIII**
…n and charisma templates for new tv changes

### CODE REVIEW

**Comment by scottia** [comment]
you think this will fix my issue #1844 in Alpha ??

**Comment by DariusIII** [comment]
No, this has nothing to do with your problem, it if purely the fix of the issue introduced by changes for tv processing.

**Comment by ruhllatio** [comment]
@scottia - this is STILL a problem?  Balls.  Let me check if I actually pushed the fix for that query we discussed earlier.

**Comment by scottia** [comment]
Oh yes, still an issue.  I can still click on the last page and add to the offset until I get to my "actual" last page.  I get the same results for books, audio, console & xxx as well.

It can wait until you finish dev-tv @ruhllatio 

Thanks again !

**Pull request merged**
