### PR TITLE
I forgot to add the new binary black list column in the schema

### PR DESCRIPTION
**Pull request by bfincher**

### CODE REVIEW

**Comment by Bart39** [comment]
this will need redoing as there are conflicts

**Comment by Wally73** [comment]
thought that Kevin already fixed something (but i can be mistaken)

**Comment by Bart39** [comment]
he fixed the empty array issue which is why this pr will need redoing for the other fixes

**Comment by Wally73** [comment]
ah ok my bad Bart39 ;) (and yeah that array fix helped me :D )

**Comment by kevinlekiller** [comment]
Added.

**Pull request closed without merging**
