### PR TITLE
Speed up getByRssToken function

### PR DESCRIPTION
**Pull request by ghost**
Addresses issue #2437 

Changes made by this pull request.
- Added index to users table
- Removed MySQL LOWER() function from getByRssToken()

### CODE REVIEW

**Comment by b3rs3rk** [comment]
Need to add the index to the DDL file as well @Fossil01

**Comment by ghost** [comment]
Will do when im back home.

**Comment by niel** [comment]
Also need to address the underlying issue, make sure those values are already lower-cased so the check is not needed in the SQL. I can help with that part of it.

**Comment by ghost** [comment]
I think the values always are and always were lowercase. It's an API key, never seen caps being used.

**Comment by niel** [comment]
It still needs to be checked before going into the table to be certain it is. Which is how it should have been done originally as it is less processing required to sanitize it on the PHP side.

**Comment by niel** [comment]
I have some time now, I'll merge in the PR and add the extra stuff needed.

**Comment by niel** [comment]
Arrrgh! you forgot to branch.

**Comment by niel** [comment]
and hardcoded the patch number!!

**Comment by ghost** [comment]
Committed from dev to dev heh. I was in a hurry 😝

**Comment by ghost** [comment]
Delete the pr if u will. Can fix tonight.

**Comment by niel** [comment]
I'm working through it already. Will finish it off

**Comment by ghost** [comment]
Hey @niel I have found more of these LOWER() queries which are not needed and can be replaced with strtolower.

https://github.com/nZEDb/nZEDb/blob/8e32d7213a9731bfa601ec731ff05120af756f91/misc/testing/Various/sabnzbd_control.php#L23

https://github.com/nZEDb/nZEDb/blob/2633d35edacd79bfcfef663924a8f29694a5da99/nzedb/Users.php#L435

https://github.com/nZEDb/nZEDb/blob/2633d35edacd79bfcfef663924a8f29694a5da99/nzedb/Users.php#L448

**Pull request merged**
