### PR TITLE
Remove 10-tvrage_titles.tsv and scripts used to pupulate that table.

### PR DESCRIPTION
**Pull request by DariusIII**
Addresses no specific issue.

Changes made by this pull request.
- Remove 10-tvrage_titles.tsv
- Remove scripts used to populate that table, as they are not used anymore

### CODE REVIEW

**Comment by b3rs3rk** [comment]
Was the table already removed from schema?

**Comment by DariusIII** [comment]
The table itself does not exist in mysql_ddl.sql

**Comment by niel** [comment]
Table was removed from schema so as not to create useless table for new users. The existing table hasn't had a patch to remove it because we were going to investigate using the existing data to populate the videos table, as I recall.

**Comment by DariusIII** [comment]
That is useless now as we are using different method to populate those tables and tvrage_titles does not serve any purpose now.

**Comment by b3rs3rk** [comment]
The table is trash, no use keeping it.

**Comment by niel** [comment]
I was just giving some context, not arguing for keeping it. :-) Should we ever want the data it will still be there in history, so removing it isn't a problem.

**Pull request merged**
