### PR TITLE
Fix notices in various web pages.

### PR DESCRIPTION
**Pull request by kevinlekiller**
Some pages still have notices, I will do them some other day.

### CODE REVIEW

**Comment by zetas** [comment]
Oh no, kevin's messing with the front-end... :P

**Comment by kevinlekiller** [comment]
I was tired I couldn't use many pages because xdebug was inserting html wherever there was a notice.

**Comment by kevinlekiller** [comment]
I couldn't even log in because there was like 5 notices on the login page lol

**Comment by zetas** [comment]
Thats weird. I haven't seen any notices on mine. I guess I fixed them all already.

**Comment by kevinlekiller** [comment]
I think they are not displayed with production php.ini settings.

**Pull request merged**
