### PR TITLE
Allow max parts to be specified in TMUX setting.  Similar to existing…

### PR DESCRIPTION
**Pull request by bfincher**
… max collections setting

### CODE REVIEW

**Comment by Bart39** [comment]
not sure on this change (qqually i am not sure about the existing functionality) as stopping bin / backfill updates will just leave you with more incomplete collections.
will take a steer from the other devs

**Comment by DariusIII** [comment]
Specifying max parts and stopping updates, in this context, is counter productive.

**Comment by bfincher** [comment]
We already have the capability to stop updates based on max collections.  This is necessary when doing massive backfills and imports to keep the parts table from growing to tens of millions of rows and causing performance to grind to a halt.

**Comment by Bart39** [comment]
yes i know, but as i said i don't like how that is implemented either, it's counter-productive as the only way you'll clear parts / binaries / collections is by creating complete collections which means you need to carry on downloading parts

**Comment by bfincher** [comment]
I think you would be 100% correct if not for the issue of lots of collections never being considered "completed" until the 2 hour interval has passed.

**Comment by Bart39** [comment]
thats a side issue and is mostly caused by subject missing the parts count (which we can't get around).
anyways as i said i'll discuss with the other dev's

**Comment by bfincher** [comment]
Thanks.  And I understand if you want to reject this one based on the dislike of the original feature.

**Pull request closed without merging**
